// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYAWqJ9FdJxSWE95qACDyUPXf1z2882ZE',
    appId: '1:1009189603519:web:c3e6ca5cadb8efe9349e0a',
    messagingSenderId: '1009189603519',
    projectId: 'verstand-2023',
    authDomain: 'verstand-2023.firebaseapp.com',
    databaseURL: 'https://verstand-2023-default-rtdb.firebaseio.com',
    storageBucket: 'verstand-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9Zv_zEP_-gFof4WtBvt6PeenVKHryGU',
    appId: '1:1009189603519:android:4db212c2dd20cba4349e0a',
    messagingSenderId: '1009189603519',
    projectId: 'verstand-2023',
    databaseURL: 'https://verstand-2023-default-rtdb.firebaseio.com',
    storageBucket: 'verstand-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5n8qj85N1Fj9sdiaCx3U6HQ6h6aX5nE',
    appId: '1:1009189603519:ios:7a5d136e0617bf00349e0a',
    messagingSenderId: '1009189603519',
    projectId: 'verstand-2023',
    databaseURL: 'https://verstand-2023-default-rtdb.firebaseio.com',
    storageBucket: 'verstand-2023.appspot.com',
    iosClientId: '1009189603519-p0vs31288taut9o7dv2cc2qug4kulhh2.apps.googleusercontent.com',
    iosBundleId: 'com.verstand.verstand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5n8qj85N1Fj9sdiaCx3U6HQ6h6aX5nE',
    appId: '1:1009189603519:ios:7a5d136e0617bf00349e0a',
    messagingSenderId: '1009189603519',
    projectId: 'verstand-2023',
    databaseURL: 'https://verstand-2023-default-rtdb.firebaseio.com',
    storageBucket: 'verstand-2023.appspot.com',
    iosClientId: '1009189603519-p0vs31288taut9o7dv2cc2qug4kulhh2.apps.googleusercontent.com',
    iosBundleId: 'com.verstand.verstand',
  );
}
